subject(id,name,marks,total_marks,grade,semester)

create table subject(
	int serial primary key,
	name varchar(100),
	marks int,
	total_marks int,
	grade varchar(3),
	semester int
)

select * from subject
insert into subject values(1,'Electrodynamics',250,600,'C',1)
insert into subject values(2,'Complex_analysis',300,600,'B	',2)
insert into subject values(3,'Quantum_mechanics',550,600,'A',3)
insert into subject values(4,'Nuclear_physics',150,600,'C',4)
insert into subject values(5,'Solid_state',350,600,'B',1)
insert into subject values(6,'Electrodynamics',226,600,'B',2)
insert into subject values(7,'Complex_analysis',430,600,'A',3)
insert into subject values(8,'Quantum_mechanics',441,600,'A',4)
select * from subject
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',299,600,'B',2)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',335,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',599,600,'A',4)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',468,600,'A',1)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',120,600,'C',1)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',283,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',256,600,'B',4)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',379,600,'B',1)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',450,600,'A',2)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',363,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',120,600,'C',4)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',599,600,'A',1)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',469,600,'A',3)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',190,600,'C',4)
select * from subject
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',590,600,'A',1)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',221,600,'C',2)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',541,600,'A',3)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',480,600,'A',4)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',221,600,'B',1)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',356,600,'B',2)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',583,600,'A',3)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',555,600,'A',4)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',463,600,'A',1)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',190,600,'C',2)
select * from subject
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',296,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',586,600,'A',4)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',549,600,'B',1)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',520,600,'A',2)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',251,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',541,600,'A',4)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',364,600,'B',1)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',356,600,'B',2)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',258,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',125,600,'C',4)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',197,600,'C',1)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',280,600,'B',2)
select * from subject
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',570,600,'A',3)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',256,600,'B',4)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',489,600,'A',1) 
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',168,600,'C',2) 
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',441,600,'A',3) 
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',364,600,'A',4) 
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',169,600,'C',1) 
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',280,600,'B',2) 
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',333,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',492,600,'A',4)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',567,600,'A',1)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',479,600,'A',2)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',367,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',267,600,'B',4)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',169,600,'C',1)
select * from subject
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',67,600,'C',2)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',513,600,'A',3)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',462,600,'A',4)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',324,600,'B',1)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',234,600,'B',2)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',128,600,'C',3)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',46,600,'C',4)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',299,600,'B',2)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',335,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',599,600,'A',4)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',468,600,'A',1)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',120,600,'C',1)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',283,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',256,600,'B',4)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',379,600,'B',1)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',450,600,'A',2)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',363,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',120,600,'C',4)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',599,600,'A',1)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',469,600,'A',3)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',190,600,'C',4)
select * from subject
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',590,600,'A',1)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',221,600,'C',2)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',541,600,'A',3)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',480,600,'A',4)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',221,600,'B',1)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',356,600,'B',2)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',583,600,'A',3)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',555,600,'A',4)
insert into subject(name,marks,total_marks,grade,semester)values('Complex_analysis',463,600,'A',1)
insert into subject(name,marks,total_marks,grade,semester)values('Quantum_mechanics',190,600,'C',2)
insert into subject(name,marks,total_marks,grade,semester)values('Nuclear_physics',296,600,'B',3)
insert into subject(name,marks,total_marks,grade,semester)values('Solid_state',586,600,'A',4)
insert into subject(name,marks,total_marks,grade,semester)values('Electrodynamics',549,600,'B',1)
